CC-30037: shopping cart with products display no items sum.
spryker-shop/b2b-demo-marketplace pull request #171
Opened 2023-07-17 17:29 UTC by sakharova-yuliia

#### Overview

- Ticket: https://spryker.atlassian.net/browse/CC-30037

###### Optional

- Core PR: URL_HERE

###### Change log

{Relevant changes for project level go here. Those will be copied to the release log for suite if necessary.}

2023-07-20 10:33 UTC, FRITS-Kh requested changes

2023-07-20 10:33 UTC, FRITS-Kh commented on src/Pyz/Yves/CartPage/Theme/default/components/organisms/cart-sidebar/cart-sidebar.twig
> +                {% endfor %}
The `data.transformedCartItems` uses only for the counter.
So it should be prepared outside instead.

2023-07-25 10:51 UTC, FRITS-Kh requested changes

2023-07-25 10:51 UTC, FRITS-Kh commented on src/Pyz/Yves/CartPage/Theme/default/templates/page-layout-cart/page-layout-cart.twig
> +            {% endfor %}
To increase readability.
```suggestion
        {% set cartItemsCount = 0 %}
        {% for cartItem in transformedCartItems %}
                {% set cartItemsCount = cartItemsCount + cartItem.quantity %}
        {% endfor %}

        <div class="grid grid--gap">
```

2023-07-26 10:16 UTC, abitskil approved these changes

2023-07-26 11:37 UTC, FRITS-Kh approved these changes

2023-07-28 10:04 UTC, merged