CC-30070 Fixed table actions alignment.
spryker-shop/b2b-demo-marketplace pull request #296
Opened 2023-12-19 11:30 UTC by danilmoro3

Ticket: https://spryker.atlassian.net/browse/CC-30070

2023-12-19 13:02 UTC, FRITS-Kh requested changes

2023-12-19 14:07 UTC, danilmoro3 commented on src/Pyz/Yves/SalesReturnPage/Theme/default/views/return-list/return-list.twig
> +    </td>
This block is fully overridden below in the template.

2023-12-19 17:25 UTC, FRITS-Kh requested changes

2023-12-19 17:25 UTC, FRITS-Kh commented on src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-table/order-table.scss
> +            white-space: nowrap;
It can affect the structure.

2023-12-19 17:25 UTC, FRITS-Kh commented on src/Pyz/Yves/MultiCartPage/Theme/default/components/molecules/quote-table/quote-table.twig
>                      {% endif %}
Please only use the widget with `td` added inside.

2023-12-19 17:25 UTC, FRITS-Kh commented on src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
> +                &#{$name}__actions {
Why is it placed into `td`?

2023-12-19 17:46 UTC, danilmoro3 commented on src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss
> +                &#{$name}__actions {
To override default padding.

2023-12-19 18:09 UTC, FRITS-Kh approved these changes

2023-12-20 11:46 UTC, FRITS-Kh approved these changes

2023-12-20 11:46 UTC, merged