Release 202211.0
spryker-shop/b2b-demo-marketplace pull request #43
Opened 2022-11-23 10:06 UTC by DmitryLymarenko

### Overview

Release 202211.0

2022-11-24 19:07 UTC, FRITS-Kh approved these changes

2022-11-24 19:26 UTC, FRITS-Kh requested changes

2022-11-24 19:26 UTC, FRITS-Kh commented on .github/workflows/ci.yml
> +                  vendor/bin/console frontend:yves:install-dependencies
Also, the `node-version` version must be changed from `12` to `16`.
```suggestion
                  vendor/bin/console frontend:project:install-dependencies -vvv
```

2022-11-24 19:29 UTC, limeeugenia approved these changes

2022-11-25 09:35 UTC, FRITS-Kh requested changes

2022-11-25 09:35 UTC, FRITS-Kh commented on .github/workflows/ci.yml
> -              run: yarn mp:test
The test should be, but with NPM
```
run: npm run mp:test
```

2022-11-25 13:59 UTC, limeeugenia approved these changes

2022-11-25 17:32 UTC, merged