CC-24698: Fixed discontinued product attributes label.
spryker-shop/b2b-demo-marketplace pull request #63
Opened 2023-03-21 15:01 UTC by sakharova-yuliia

#### Overview

- Ticket: https://spryker.atlassian.net/browse/CC-24698

2023-03-22 11:03 UTC, danilmoro3 approved these changes

2023-03-22 11:03 UTC, danilmoro3 commented on src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/variant-configurator/variant-configurator.twig
> +            {% set selectedUrlParameter = [('attribute[' ~ selectedAttributeName ~ ']')| url_encode, selectedAttributeValue] | join('=') %}
```suggestion
            {% set selectedUrlParameter = [('attribute[' ~ selectedAttributeName ~ ']') | url_encode, selectedAttributeValue] | join('=') %}
```

2023-03-22 15:54 UTC, FRITS-Kh requested changes
The same comments https://github.com/spryker-shop/b2b-demo-shop/pull/143#pullrequestreview-1352952267

2023-03-22 16:31 UTC, ilyakubanov requested changes
- please revert downgrading the modules versions (not shown as diff but the version in integration branch is downgraded)

2023-03-23 14:41 UTC, FRITS-Kh approved these changes

2023-03-23 14:41 UTC, FRITS-Kh commented on src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/variant-configurator/variant-configurator.twig
> +            {% set selectedUrlParameter = ('attribute[' ~ selectedAttributeName ~ ']')| url_encode ~ '=' ~ selectedAttributeValue %}
```suggestion
            {% set selectedUrlParameter = ('attribute[' ~ selectedAttributeName ~ ']') | url_encode ~ '=' ~ selectedAttributeValue %}
```

2023-03-23 19:02 UTC, ilyakubanov approved these changes

2023-03-24 13:17 UTC, merged