CC-26385: Integrated ajax rendering of the cart page
spryker-shop/b2b-demo-marketplace pull request #80
Opened 2023-04-12 10:18 UTC by andrew-maslov

#### Overview

- Ticket: https://spryker.atlassian.net/browse/CC-26385

2023-04-12 12:30 UTC, danilmoro3 requested changes

2023-04-12 12:30 UTC, danilmoro3 commented on src/Pyz/Yves/ProductReviewWidget/Theme/default/components/molecules/review-average-display/review-average-display.twig
>      <div class="review-average-display__average-rating">
```suggestion
    <div class="{{ config.name }}__average-rating">
```

2023-04-12 14:45 UTC, danilmoro3 approved these changes

2023-04-19 08:19 UTC, FRITS-Kh approved these changes

2023-04-20 12:43 UTC, merged