FRW-1205: Integrated Propel changes
spryker-shop/b2b-demo-marketplace pull request #91
Opened 2023-05-02 11:53 UTC by olhalivitchuk

#### Overview

- Ticket: https://spryker.atlassian.net/browse/FRW-1205

2023-05-02 12:26 UTC, yaroslav-spryker requested changes

2023-05-02 12:26 UTC, yaroslav-spryker commented on composer.json
> +            "sllh/composer-versions-check": true
Do we need this plugin?

2023-05-02 12:26 UTC, yaroslav-spryker commented on config/Shared/config_default.php
> +$config[PropelReplicationCacheConstants::IS_REPLICATION_ENABLED] = (bool)$config[PropelConstants::ZED_DB_REPLICAS];
This setting will enable caching when replicas enabled. But I remember that we will integrate this feature by default as always disabled.
@gechetspr could you please advice how we do in this case?

2023-05-02 15:54 UTC, yaroslav-spryker approved these changes

2023-05-02 16:47 UTC, asmarovydlo approved these changes

2023-05-10 06:30 UTC, dimitriyTsemma requested changes

2023-05-10 07:01 UTC, gechetspr commented on src/Orm/Zed/Country/Persistence/SpyCountryStore.php
> +class SpyCountryStore extends BaseSpyCountryStore
just a question. This looks like a part of DS. This is smth that we missed to integrate with it?

2023-05-10 07:05 UTC, gechetspr approved these changes

2023-05-12 09:34 UTC, merged